name: users_creators
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  components:
    path: ../components
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.6.0
  freezed_annotation: ^2.0.3
  freezed: ^2.0.3+1
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  http: ^0.13.4
  auto_route: ^4.0.1
  flutter_native_splash: ^2.2.3+1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  dropdown_button2: ^1.6.3
  package_info: ^2.0.2
  image_picker: ^0.8.5+3
  intercom_flutter: ^7.3.0
  copy_with_extension_gen: ^4.0.2
  scrollable_clean_calendar: ^1.4.0
  scrollable_positioned_list: ^0.3.2
  keyboard_actions: ^4.0.1
  cached_network_image: ^3.2.1
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  url_launcher: ^6.1.5
  pin_code_fields: ^7.4.0
  avatar_view: ^1.0.1
  uuid: ^3.0.6
  youtube_player_flutter: ^8.1.0
  flutter_speed_dial: ^6.0.0
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  google_mobile_ads: ^2.0.1
  webview_flutter: ^3.0.4
  flutter_svg_provider: ^1.0.3
  custom_timer: ^0.1.2
  in_app_purchase: ^3.0.7
  smooth_page_indicator: ^1.0.0+2
  textfield_search: ^0.10.0
  bloc_concurrency: ^0.2.0
  flutter_slidable: ^2.0.0
  syncfusion_flutter_charts: ^20.2.46
  pausable_timer: ^1.0.0+6
  draggable_bottom_sheet: ^1.0.2
  sliding_sheet: ^0.5.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  auto_route_generator: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_splash/new_splash.png
  # branding: assets/images/app_splash/splash_beta_branding.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFit

  android_12:
    image: assets/images/app_splash/new_splash.png
    icon_background_color: "#FFFFFF"

  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon/app_icon.png"

flutter:
  assets:
    - .env
    - assets/images/
    - assets/images/onboarding/
    - lib/src/core/lang/
    - assets/images/app_splash/
    - assets/images/auth_page/
    - assets/images/dashboard/
    - assets/images/corousel/
    - assets/images/creator/
    - assets/images/library/
    - assets/images/create_session/
    - assets/images/workout_popup/
    - assets/images/onboarding_creator/
    - assets/images/app_icon/
    - assets/images/training_session/
    - assets/images/session/
    - assets/images/calendar/

    - assets/icons/creator/
    - assets/icons/welcome_page/
    - assets/icons/start_session/
    - assets/icons/calendar_header/
    - assets/icons/dashboard/
    - assets/icons/top_panel/
    - assets/icons/top_panel_library/
    - assets/icons/login/
    - assets/icons/discover/
    - assets/icons/settings/
    - assets/icons/create_session/
    - assets/icons/workout_popup/
    - assets/icons/onboarding_creator/
    - assets/icons/training_session/
    - assets/icons/session/

  fonts:
   - family: SF Pro
     fonts:
       - asset: assets/fonts/SFPro-Light.ttf
         weight: 200
       - asset: assets/fonts/SFPro-Regular.ttf
         weight: 400
       - asset: assets/fonts/SFPro-Medium.ttf
         weight: 500
       - asset: assets/fonts/SFPro-Semibold.ttf
         weight: 600
       - asset: assets/fonts/SFPro-Bold.ttf
         weight: 700
       - asset: assets/fonts/SFPro-Heavy.ttf
         weight: 800
       - asset : assets/fonts/SFPro-Black.ttf
         weight: 900
   - family: Orbitron
     fonts:
       - asset: assets/fonts/Orbitron-Regular.ttf
         weight: 400

  uses-material-design: true