abstract class ChangeIndicatorLengthEvent{}

class AddIndicatorLengthEvent extends ChangeIndicatorLengthEvent{}

class MinusIndicatorLengthEvent extends ChangeIndicatorLengthEvent{}

class InitialStateIndicatorLengthEvent extends ChangeIndicatorLengthEvent{}