name: components
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  http: ^0.13.4
  auto_route: ^4.0.1
  scrollable_positioned_list: ^0.3.2
  intl: ^0.17.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1
  video_player: ^2.4.5
  chewie: ^1.3.4
  flick_video_player: ^0.5.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11


flutter:
  # assets:

  uses-material-design: true